version: '3.8'

services:
  ui:
    image: pmckee/widgets-ui:1.0.0
    build: 
      context: ./ui
    ports:
      - "3000:80"
    networks: 
      - frontend
      - backend
  
  server:
    image: pmckee/widgets-server:1.0.0
    build:
      context: ./server
    ports:
      - "8080:80"
    networks: 
      - backend

networks: 
  frontend:
  backend: